"Vim: configuration file 
" disable vi compatibility (emulation of old bugs)
set nocompatible
filetype plugin indent on
" use indentation of previous line
set autoindent
" use intelligent indentation for C
set smartindent
set ruler
set wildmode=list:longest
" configure tabwidth and insert spaces instead of tabs
set tabstop=2        " tab width is 2 spaces
set shiftwidth=2     " indent also with 2 spaces
set expandtab        " expand tabs to spaces

" wrap lines at 120 chars. 80 is somewaht antiquated with nowadays displays.
set wrap
set textwidth=80
set colorcolumn=+1

" turn syntax highlighting on
filetype on
filetype plugin on
filetype indent on
syntax on
set t_Co=256
syntax enable
colorscheme brogrammer

set wrap linebreak nolist
"Since I'm sloppy with my shift key, :Wq maps to :wq
command W w
command Wq wq

" Uses filename regex for searching, not contents (seems to get better results)
let g:ctrlp_regexp = 1
set wildignore+=*/tmp/*,*.so,*.swp,*.o,*.a,*.zip,*.beam,*/.eunit/*,*.pyc
set runtimepath^=~/.vim/bundle/ctrlp.vim
" Faster ctrlp indexing with ag
"let g:ctrlp_user_command = 'ag %s -i --nogroup --hidden --ignore .git --ignore .svn --ignore .hg --ignore "**/*.pyc" --ignore .DS_Store --ignore "**/*.ebin" --ignore "**/*.swp" --ignore "**/*.so" -g ""'
" turn line numbers on
set number
" highlight matching braces
set showmatch
" intelligent comments
set comments=sl:/*,mb:\ *,elx:\ */

let g:clang_library_path='/Library/Developer/CommandLineTools/usr/lib'

"set tags=./tags,tags;
" Install OmniCppComplete like described on http://vim.wikia.com/wiki/C++_code_completion
" This offers intelligent C++ completion when typing ‘.’ ‘->’ or <C-o>
" Load standard tag files
set tags+=~/.vim/tags/cpp
set tags+=~/.vim/tags/gl
set tags+=~/.vim/tags/sdl
set tags+=~/.vim/tags/qt4
